### ISSUE TITLE
ValueError: Shape (32, 768) must have rank 3

### ISSUE THREAD

**Issue by samarth92** [carpedm20/attentive-reader-tensorflow#10]
I am getting the following error on running this on version 0.9. 
I have already #from tensorflow.models.rnn import rnn, rnn_cell statements and replaced them with tf.nn.**.

 [*] Building Deep LSTM...
 [*] Loading vocab from data/cnn/cnn.vocab100000 ...
 [*] Loading vocab finished.
Traceback (most recent call last):
  File "main.py", line 49, in <module>
    tf.app.run()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 30, in run
    sys.exit(main(sys.argv))
  File "main.py", line 44, in main
    FLAGS.data_dir, FLAGS.dataset)
  File "/home/development/samarth/Workspace/Accenture_VA/attentive-reader-tensorflow-master/model/deep_lstm.py", line 91, in train
    self.prepare_model(data_dir, dataset_name, vocab_size)
  File "/home/development/samarth/Workspace/Accenture_VA/attentive-reader-tensorflow-master/model/deep_lstm.py", line 69, in prepare_model
    for idx, nstarts in enumerate(tf.unpack(self.nstarts))])
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/array_ops.py", line 251, in slice
    return gen_array_ops._slice(input_, begin, size, name=name)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/gen_array_ops.py", line 1634, in _slice
    name=name)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/op_def_library.py", line 704, in apply_op
    op_def=op_def)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 2262, in create_op
    set_shapes_for_outputs(ret)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 1702, in set_shapes_for_outputs
    shapes = shape_func(op)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/array_ops.py", line 1054, in _SliceShape
    input_shape.assert_has_rank(ndims)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/tensor_shape.py", line 621, in assert_has_rank
    raise ValueError("Shape %s must have rank %d" % (self, rank))
ValueError: Shape (32, 768) must have rank 3

**Comment by nicolettiant89** [comment]
hi, have you solved the issue above by your own? @samarth92  Thanks

**Comment by nicolettiant89** [comment]
i have the same issue too, someone can help??

**Comment by jsheng0901** [comment]
> i have the same issue too, someone can help??

Hi recently I'm do the same topic. I face the same issue. have you solved this issue?

**Comment by jsheng0901** [comment]
have you solved this issue ? @nicolettiant89  Really thank you!
